services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/mydb

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
